name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: compile & test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Check out code
        uses: actions/checkout@v1
      - name: Lint
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
